/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_Main */

#ifndef _Included_src_Main
#define _Included_src_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_Main
 * Method:    setup
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_src_Main_setup
  (JNIEnv *, jclass, jstring);

/*
 * Class:     src_Main
 * Method:    execute
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/StringBuilder;)Z
 */
JNIEXPORT jboolean JNICALL Java_src_Main_execute
  (JNIEnv *, jclass, jstring, jobjectArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
